### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by s256** [catalyst/moodle-auth_basic#2]
Hi,
in my case (Moodle 3.1.1+ (Build: 20160728) ) I'm not able to save any settings of your plugin. 
Is it still compatible with moodle 3.1.1? I also don't get any "pop up" login window as I would expect from basic auth. 
Our plan is to use basic auth for moodle to enable SSO for our users.

Best
Se

**Comment by brendanheywood** [comment]
> in my case (Moodle 3.1.1+ (Build: 20160728) ) I'm not able to save any settings of your plugin. 

I can't reproduce this, please provide more details? In particular on save do you get the settings page again, or do you go back to the manage page?

> Is it still compatible with moodle 3.1.1? I also don't get any "pop up" login window as I would expect from basic auth. 

Yes it is compatible, however you almost never actually want to use this with real human users, only for scripts, it is designed to work side by side with other auth methods. If you really really want the popup prompt for everyone then turn this setting on but this will break other forms of authentication:

![image](https://cloud.githubusercontent.com/assets/187449/17612543/8eab79d6-6096-11e6-941f-5078cddea3da.png)

> Our plan is to use basic auth for moodle to enable SSO for our users.

Honestly this sounds horrible. At best it will only ever be 'same sign on' not 'single sign on' and will be an utterly horrible user experience, and nobody will be able to logout which is a pretty big security issue. If you want SSO then use a protocol designed for it such as SAML (or OIDC) see this plugin:

https://github.com/CatalystIT-AU/moodle-auth_saml2

If need consultancy support with SAML SSO send us an email: enquiries@catalyst-au.net

**Comment by s256** [comment]
After pressing "save changes" I get redirected to the manage page. Clicking again on the settings page I see the same unchanged "standard" settings as before.  Environment: nginx + php-fpm pool . No PHP or nginx errors in the logs.

> Honestly this sounds horrible. At best it will only ever be 'same sign on' not 'single sign on' and will be an utterly horrible user experience, and nobody will be able to logout which is a pretty big security issue. If you want SSO then use a protocol designed for it such as SAML (or OIDC) see this plugin:
> https://github.com/CatalystIT-AU/moodle-auth_saml2

Thanks, I will have a look at your plugin. We didn't decide how to implement SSO, we just came across this possibility. But you are right SAML would be a better option.
