### ISSUE TITLE
3.10 - PHPUnit fails

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-auth_basic#24]
PHPUnit test environment setup complete.

PHP Fatal error:  Declaration of auth_basic_test::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /var/www/html/auth/basic/tests/auth_basic_test.php on line 40'
  stderr_lines: <omitted>
  stdout: |-
    Moodle 3.10 (Build: 20201109), f76515bf7b7ee0ccc3d90263ac847da8d45d8d60
    Php: 7.3.20, mysqli: 5.7.31, OS: Linux 3.10.0-1160.2.1.el7.x86_64 x86_64
  
    Fatal error: Declaration of auth_basic_test::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /var/www/html/auth/basic/tests/auth_basic_test.php on line 40

**Comment by aspark21** [comment]
Will be due to https://docs.moodle.org/dev/Writing_PHPUnit_tests#Upgrading_unit_tests_to_work_with_Moodle_3.10_and_up_.28PHPUnit_8.5.29

**Comment by aspark21** [comment]
Still an issue for 3.11

**Comment by mattporritt** [comment]
PR merged in.
