### ISSUE TITLE
user cannot login

### ISSUE THREAD

**Issue by bhavesz** [catalyst/moodle-auth_basic#6]
Hi there,
I've installed auth plugin and crawler plugin both on,
UAT.modmed.com.au 

I have followed the instruction and created a bot user with basic authentication but somehow that user cannot login and that way, plugin cannot work on our site. can you please help.

**Comment by bhavesz** [comment]
Do you have any thoughts on this?

**Comment by brendanheywood** [comment]
Sorry I am currently on extended leave, if you would like support please contact:

https://www.catalyst-au.net/content/contact-us
